services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=loggingapi;Username=postgres;Password=postgres
      Jwt__Secret: "yU16thMLT0uaBgVyDh1nU2f4ei2fxlhx3tPVnTPQPas"
      
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: loggingapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data: