services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - loggingapi.cache
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=loggingapi;Username=postgres;Password=postgres
      ConnectionStrings__Cache: "loggingapi.cache:6379"
      Jwt__Secret: "yU16thMLT0uaBgVyDh1nU2f4ei2fxlhx3tPVnTPQPas"
      Ai__BaseAddress: "http://host.docker.internal:11434"
      Ai__Model: "qwen3:8b"
      Email__Username: "LoggingApi"
      Email__Password: "nyQdap-vecved-1rikti"
      
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: loggingapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    ports:
      - 8025:8025
      - 1025:1025
    volumes:
      - ./data:/data
  
  loggingapi.cache:
    container_name: "loggingapi.cache"
    image: redis:8-alpine
    restart: always
    volumes:
      - redis_data:/data
    command: "redis-server --appendonly yes"

volumes:
  postgres_data:
  redis_data: